/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.parser;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

@Disabled
class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        fail("Not implemented.");
    }
}
